/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotreMaisonRouteImport } from './routes/notre-maison'
import { Route as NosUniversRouteImport } from './routes/nos-univers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const NotreMaisonRoute = NotreMaisonRouteImport.update({
  id: '/notre-maison',
  path: '/notre-maison',
  getParentRoute: () => rootRouteImport,
} as any)
const NosUniversRoute = NosUniversRouteImport.update({
  id: '/nos-univers',
  path: '/nos-univers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/nos-univers': typeof NosUniversRoute
  '/notre-maison': typeof NotreMaisonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/nos-univers': typeof NosUniversRoute
  '/notre-maison': typeof NotreMaisonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/nos-univers': typeof NosUniversRoute
  '/notre-maison': typeof NotreMaisonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/nos-univers' | '/notre-maison'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/nos-univers' | '/notre-maison'
  id: '__root__' | '/' | '/contact' | '/nos-univers' | '/notre-maison'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  NosUniversRoute: typeof NosUniversRoute
  NotreMaisonRoute: typeof NotreMaisonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notre-maison': {
      id: '/notre-maison'
      path: '/notre-maison'
      fullPath: '/notre-maison'
      preLoaderRoute: typeof NotreMaisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nos-univers': {
      id: '/nos-univers'
      path: '/nos-univers'
      fullPath: '/nos-univers'
      preLoaderRoute: typeof NosUniversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  NosUniversRoute: NosUniversRoute,
  NotreMaisonRoute: NotreMaisonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
